spring:
  datasource:
    url: jdbc:mysql://localhost:3306/meetin?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: root
    password: root
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
  data:
    mongodb:
      host: localhost
      port: 27017
      database: meetin
  mail:
    host: smtp.mail.yahoo.com
    port: 465
    username: radiologyreport@yahoo.com
    password: 963852123
    properties:
      mail:
        smtp:
          auth: true
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
                
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/
