spring:
  datasource:
    url: jdbc:mysql://localhost:3306/meetin?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: root
    password: root
    #initialization-mode: 
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
  data:
    mongodb:
      host: localhost
      port: 27017
      database: meetin
      
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/
logging:
  level:
    org.hibernate.sql: DEBUG
    
app:
  jwt:
    secret: MeetIn
    expiration: 604800000