feign:
  client:
    config:
      default:
        connect-timeout: 160000
        read-timeout:  160000
                
app:
  jwt:
    secret: MeetIn
    expiration: 604800000
    header: Authorization
  authorization:
    enabled:
      true